apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: login-app
type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: "CHANGE_ME"
  MYSQL_DATABASE: "login_db"
  MYSQL_USER: "login_user"
  MYSQL_PASSWORD: "CHANGE_ME"
